# Generated by Django 2.2.12 on 2021-09-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_title', models.TextField()),
                ('Desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_Name', models.TextField()),
                ('Image1', models.ImageField(upload_to='pics')),
                ('Image2', models.ImageField(upload_to='pics')),
                ('Image3', models.ImageField(upload_to='pics')),
                ('Image4', models.ImageField(upload_to='pics')),
                ('Image5', models.ImageField(upload_to='pics')),
                ('Image6', models.ImageField(upload_to='pics')),
                ('Image7', models.ImageField(upload_to='pics')),
                ('Image8', models.ImageField(upload_to='pics')),
                ('Image9', models.ImageField(upload_to='pics')),
                ('Image10', models.ImageField(upload_to='pics')),
                ('Image11', models.ImageField(upload_to='pics')),
                ('Image12', models.ImageField(upload_to='pics')),
                ('Image13', models.ImageField(upload_to='pics')),
                ('Image14', models.ImageField(upload_to='pics')),
                ('Image15', models.ImageField(upload_to='pics')),
                ('Image16', models.ImageField(upload_to='pics')),
                ('Image17', models.ImageField(upload_to='pics')),
                ('Image18', models.ImageField(upload_to='pics')),
                ('Image19', models.ImageField(upload_to='pics')),
                ('Image20', models.ImageField(upload_to='pics')),
                ('Image21', models.ImageField(upload_to='pics')),
                ('Image22', models.ImageField(upload_to='pics')),
                ('Image23', models.ImageField(upload_to='pics')),
                ('Image24', models.ImageField(upload_to='pics')),
                ('Image25', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teacher_name', models.TextField()),
                ('description_of_teacher', models.TextField()),
                ('photo', models.ImageField(null='true', upload_to='pics')),
                ('Education', models.TextField()),
            ],
        ),
    ]
